### ISSUE TITLE
Failed to get TZ variables in container

### ISSUE THREAD

**Issue by dperezq** [sibbl/hass-lovelace-kindle-screensaver#123]
Hi, I have started the container and the process is working fine, it is generating the screenshot and it is loading properly in the Kindle, but I have an issue with the timezone. It seems that the container is not getting the timezone variable correctly. This is a problem because the rendering process (I image because of the browser) is getting that time instead of my local time. 

```
 kindle-weather:
    image: sibbl/hass-lovelace-kindle-screensaver:latest
    environment:
      .
      .
      .
      - TZ=Europe/Berlin
    ports:
      - 5005:5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
```

Response of the date command inside the container, showing UTC and -2 hours (matches the result of the screenshot):
```
/app # date
Thu Apr 25 09:06:07 UTC 2024
```

I also attach the image of the current ha dashboard and the output screenshot. The local zona is also configured within the HA, indeed in the dashboard it is correctly displayed, so it is a problem with the container.  You can see the differences in the lower card but the upper card seems to work properly. Does anyone have the same issue? This is the card horizon-card

![image](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/7505361/9d765d4e-d825-4ab4-afe6-7a109d20fccc)
![image](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/7505361/f8ab051f-b8dd-4342-8ee3-cbb141763694)

I tried installing tzdata inside the container using` apk add --update tzdata` and now the time and timezone is ok, as can be seen in the command below, but the screenshot is still showing the wrong time:
```
/etc # date
Thu Apr 25 13:55:14 CEST 2024
```
Any ideas on how to solve this?
