### ISSUE TITLE
Image not captured as displayed

### ISSUE THREAD

**Issue by Coolie1101** [sibbl/hass-lovelace-kindle-screensaver#36]
The image isn't captured as displayed in HA, and is captured in grayscale even though I specified "TrueColor".

**Config**
```
  app:
    image: sibbl/hass-lovelace-kindle-screensaver:latest
    environment:
      - HA_BASE_URL=http://192.168.200.211:8123
      - HA_SCREENSHOT_URL=/lovelace-system/screenshot?kiosk
      - HA_ACCESS_TOKEN=my_ha_access_token
      - CRON_JOB=* * * * *
      - RENDERING_TIMEOUT=30000
      - RENDERING_SCREEN_HEIGHT=160
      - RENDERING_SCREEN_WIDTH=128
      - OUTPUT_PATH=/output/cover.png
      - SCALING=1
      - COLOR_MODE=TrueColor
    ports:
      - 5000:5000
    volumes:
      - ./output/:/output
```

**HA Screenshot**
![image](https://user-images.githubusercontent.com/28989417/167634343-19ebeeb7-5ca5-4ffa-82e7-8b7130234c0d.png)

**Captured Image**
![image](https://user-images.githubusercontent.com/28989417/167638208-8baae0c0-6782-4081-bdcd-f6272624c362.png)
