### ISSUE TITLE
Strange zoom issue...

### ISSUE THREAD

**Issue by totalitarian** [sibbl/hass-lovelace-kindle-screensaver#51]
When left to automatically pull the latest image, the image is all zoomed in

![image](https://user-images.githubusercontent.com/2385696/213008624-47de35ea-1a52-4ffa-b401-68b8377aea96.png)

If I then unlock and relock my kindle, the image looks fine

![image](https://user-images.githubusercontent.com/2385696/213008049-c0cf87a8-a848-4044-aec1-aebe22930471.png)

Any ideas?

Here is my docker compose

```
hass-lovelace-kindle-screensaver:
    image: sibbl/hass-lovelace-kindle-screensaver:latest
    restart: unless-stopped
    environment:
      - HA_BASE_URL=http://192.168.1.50:8123
      - HA_SCREENSHOT_URL=/lovelace-test/kindle?kiosk
      - HA_ACCESS_TOKEN=xxx
      - CRON_JOB=* * * * *
      - RENDERING_TIMEOUT=30000
      - RENDERING_DELAY=20000
      - RENDERING_SCREEN_HEIGHT=1448
      - RENDERING_SCREEN_WIDTH=1072
      - GRAYSCALE_DEPTH=8
      - COLOR_MODE=TrueColor
      - OUTPUT_PATH=/output/cover.png
      - LANGUAGE=en
      - ROTATION=0
      - SCALING=2
      - HA_BATTERY_WEBHOOK=set_kindle_battery_level
    ports:
      - 8888:5000
    volumes:
      - ./output/:/output

```
