### ISSUE TITLE
Error rendering data template: UndefinedError: 'dict object' has no attribute 'json' when trying to run Kindle battery blueprint

### ISSUE THREAD

**Issue by TomAnks** [sibbl/hass-lovelace-kindle-screensaver#75]
Not sure what I am doing wrong here, but I am receiving the above error when trying to run the automation to fetch the battery level of the Kindle.

I have:
- Applied the Kindle Online Screensaver patch
- Created 2 new entities: input_number.kindle_battery_level and input_boolean.kindle_battery_charging
- Imported the blueprint file from the instructions.
- Added the 2 new entities to the blueprint
- Set the webhook to equal the same as that defined in the add-on config.

This means that I am unable to run the automation as it errors every time. Can anyone assist?

**Comment by TomAnks** [comment]
Thank you! The new blueprint gave me the following error:

`Error: Error rendering data template: UndefinedError: 'dict object' has no attribute 'query'`

However, I am able to pull the battery life of my Kindle to display in HA, which is all I really need to do, so if the blueprint isn't required for me to be able to query the battery life then this can be closed.

**Comment by TomAnks** [comment]
Hi, I have gone through the setup again and ensured that the batteryLevel code is correct on my Kindle, but I am still encountering the same error. Do you have any other ideas for what could be the fix?

**Comment by scarolan** [comment]
I tried @sibbl 's updated blueprint but still seeing kindle_battery_level is always 0 and never gets updated.  

Fetching images is working fine.

```
Rendering http://homeassistant.local:8123/z-kindle-e-ink/0 to image...
Converting rendered screenshot of http://homeassistant.local:8123/z-kindle-e-ink/0 to grayscale png...
Finished http://homeassistant.local:8123/z-kindle-e-ink/0
2024-01-14T19:59:27.136Z: Image 1 was accessed
```

update.sh has this in it:
```
if [ 1 -eq $CONNECTED ]; then
    batteryLevel=`/usr/bin/powerd_test -s | awk -F: '/Battery Level/ {print substr($2, 0, length($2)-1) - 0}'`
    isCharging=`/usr/bin/powerd_test -s | awk -F: '/Charging/ {print substr($2,2,length($2))}'`
    if wget -q "$IMAGE_URI?batteryLevel=$batteryLevel&isCharging=$isCharging" -O $TMPFILE; then
		mv $TMPFILE $SCREENSAVERFILE
		logger "Screen saver image updated"
```

and my automation is the same as the one @TomAnks created.  (webhook_id obfuscated)

```
alias: Kindle - Battery Level
description: Battery level for Kindle Weather Display
trigger:
  - platform: webhook
    allowed_methods:
      - POST
      - PUT
    local_only: false
    webhook_id: 7AA751FBRANDOMHEX9ABCDEFGA85
condition: []
action:
  - service: input_number.set_value
    data: "{{ trigger.json.batteryLevel }}"
    target:
      entity_id: input_number.kindle_battery_level
mode: single
```

I tried turning local_only to false but that didn't seem to help either.

**Comment by seranor-ha** [comment]
Hi, 
I also struggle with this issue, also tried to use "trigger.query" but so far no difference and no value sadly. It would be nice to have a step by step guide how to troublshoot this somehow. 
Happy new year by the way :-)
Stephan

**Comment by TomAnks** [comment]
@seranor-ha This has actually been working correctly for me for some time now. Looking at my automation, it now includes a separate action for `input_number.set_value`, can you see if this works? (Keeping in mind I'm not sure what fixed the eventual issue on my end - but this is working for me!)

```
alias: Kindle - Battery Level Webhook
description: >-
  Sends the value of the Kindle battery level to Home Assistant. Used to display
  the battery level on the Kindle dashboard and send alerts when Kindle needs
  charging.
triggers:
  - allowed_methods:
      - POST
      - PUT
    local_only: true
    webhook_id: set_kindle_battery_level_XXXXXXXXXXXXX
    trigger: webhook
conditions: []
actions:
  - data_template:
      value: "{{ trigger.json.batteryLevel }}"
    target:
      entity_id: input_number.kindle_battery_level
    action: input_number.set_value
mode: single
```

**Comment by seranor-ha** [comment]
If I try to use this, I got: 

<img width="546" height="48" alt="Image" src="https://github.com/user-attachments/assets/4c657268-4804-4ce0-93ab-0a5eb5e6e17e" />

**Comment by TomAnks** [comment]
@seranor-ha Try changing the automation yaml to use 'trigger' instead of 'triggers' like so:

```
trigger:
  - platform: webhook
    allowed_methods:
      - POST
      - PUT
    local_only: true
    webhook_id: set_kindle_battery_level_XXXXXXXXXXXXX
```
